### ISSUE TITLE
why re-enter pin when leaving the app?

### ISSUE THREAD

**Issue by ezal** [obsidiansystems/ledger-app-tezos#139]
Whenever I leave the Tezos Baking App I have to reenter the pin. 
Is this on purpose?
This does not happen for other applications.

The version of the app is 2.2.5

**Comment by 3noch** [comment]
This is because the baking application prevents the ledger from going into "sleep" mode. Once the ledger enters sleep mode you must enter your pin to re-enter the dashboard. But because the baking application prevents this it requires that you enter your pin when you exit it. The reason behind this interaction is that the baking application is designed to run indefinitely and therefore run unattended. A potential attack vector involves a user leaving the baking application open and an attacker getting physical access to the ledger while the owner is away. If the baking application did not require a pin upon exit, the attacker could exit the baking app and be brought back into the dashboard where they could access a wallet *without ever entering a pin*.

**Comment by ezal** [comment]
This makes sense, thank you.

I was using it for debugging and had to switch between apps often, and then
it is quite tiring... But I guess there is no way around it.
