### ISSUE TITLE
"This app is not genuine"

### ISSUE THREAD

**Issue by utdrmac** [obsidiansystems/ledger-app-tezos#149]
Just installed latest wallet 2.2.7 using linux/command-line. Ledger says "This app is not genuine" when I launch it.

Why?

**Comment by mikereinhart** [comment]
This happens whenever an application is not installed via Ledger Live because the app isn't signed by Ledger's key. I believe this behavior first started during Ledger firmware 1.6.0. The app is otherwise identical to the one downloadable from Ledger Live, though v2.2.7 is not yet available there. [Here's the PR for that.](https://github.com/LedgerHQ/app-tezos/pull/15)

We should make a note of this in our docs for future users who are also curious about this message. Thanks for opening the issue!

**Comment by mikereinhart** [comment]
Hi @utdrmac - we've merged a doc update to make this clearer. I'm inclined to close this issue now, please let me know if you have anymore questions! Thanks

**Comment by utdrmac** [comment]
Yes, this can close. Thanks. That PR is 4 months old, by the way. Can we expect a merge soon? I understand there's a new release of LL scheduled for tues. Will 2.2.7 be included? Is there some holdup?

**Comment by mikereinhart** [comment]
Backstory - That PR was originally for the [v2.2.6 release](https://github.com/obsidiansystems/ledger-app-tezos/releases/tag/v2.2.6), which added two bakers to the list in the app. When we went to make a PR for v2.2.7 2 weeks ago, it added it to our existing PR for v2.2.6.

Right now there is a hold up related to Nano X support - you'll notice v2.2.7 release is currently only for the Nano S. QA and dev for that device is more restrictive (and made worse by full-remote work) so it has taken longer. We've QAed, found a UI bug that should be addressed, and we plan to fix it next week. It is far easier for Ledger to release both at the same time, so I'd expect availability in Ledger Live shortly after that. Apologies for any delays! In the meantime, the version you've manually installed will work great.
