### ISSUE TITLE
Operation with more than 3 transactions not possible?

### ISSUE THREAD

**Issue by vindberg** [obsidiansystems/ledger-app-tezos#71]
Hi, first of all great work on the wallet. 

Im trying to do bulk operations with multiple transactions. It seems that the Ledger doesn't receive the call when there are more than 3 transactions in one operation. Is that a limit?

Im calling from the browser.

**Comment by 3noch** [comment]
There is a bug in the currently release Wallet app on Ledger Live that causes large operations to fail. That bug has been fixed in `develop` if you want to build/install yourself. Also, in `develop`, signing a batch operation will cause the app to show you a blake2b hash of the operation instead of each field individually. You can try to confirm the hash by recomputing the operation yourself. This feature is planned for the next release along with documentation for how to use it.

**Comment by vindberg** [comment]
Hi, thanks for the prompt reply. We will wait for the official release then.

Great work so far.

**Comment by matthewbauer** [comment]
This is resolved with Tezos Ledger 2.0.0+.
